###In the name of God
###Copyright: Mohammad Reza Bateni - 2022 ([LinkedIn](https://ir.linkedin.com/in/mohammad-reza-bateni-a58936142))([Email](mailto:Bateni1380@gmail.com))


##Numpy

Numpy is a python library adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. ([Wikipedia](https://en.wikipedia.org/wiki/NumPy))


This library is written in C so its a lot faster than regular python, so its better to use numpy arrays, ratter than writing nested loops, because it makes a huge difference in running time of your application.

By the way, performing calculations with numpy arrays and matrices allow's your computer to use benefits of multiprocessing so your program will execute even faster.

###Installing Numpy

To install numpy, how should write pip install numpy in your commomd line, if you have problem installing numpy check out [here](https://numpy.org/install/)



In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Then you should import this library at the begining of your program, then you are ready to go.

In [ ]:
import numpy as np

###Proving that numpy arrays are much faster than nested loops (Optional)

Theoretically, numpy arrays are faster than nested loops. because this library is written in C and C is so much faster than Python ([source](https://peter-jp-xie.medium.com/how-slow-is-python-compared-to-c-3795071ce82a)).
and the other reason  is performing calculations with numpy arrays and matrices allow's your computer to use benefits of multiprocessing, so your program will execute even faster.

Lets see if numpy is really faster than reqular python.

In this program, I made a calculation for every elements in y that is 4000\*4000 large. And each time, I printed the elapsed time to see if numpy is faster or not.

In [ ]:
import time

start_time = time.time()
x = [[[1]*3]*4000]*4000
y = [[0]*4000]*4000
for i in range(4000):
  for j in range(4000):
    y[i][j] = (x[i][j][0]+x[i][j][1]+x[i][j][2])
print('Time elapsed with nested loop : ', time.time()-start_time, ' seconds.')

start_time = time.time()
x = np.ones([4000,4000,3])
y = np.zeros([4000,4000])
y = x[:][:][0]+x[:][:][1]+x[:][:][2]
print('Time elapsed with numpy : ', time.time()-start_time, ' seconds.')



Time elapsed with nested loop :  7.238420009613037  seconds.
Time elapsed with numpy :  0.11594986915588379  seconds.


Now we can see that numpy did the same calculation, 65 times faster!!!





###Defining a numpy array

In [ ]:
# Creating arrays
a = np.array([1, 2, 3]) # Create a rank 1 array (vector)
print('1-d array (vector) : ', a)
print('type: ',type(a),' shape:', a.shape,' value at (1) :', a[0]) # Print type and shape and values of the array

b = np.array([[1, 2],
              [3, 4]]) # Create a rank 2 array (matrice)
print('\n2-d array (matrice) : ')
print(b)
print('type: ',type(b),' shape:', b.shape,' value at (1,0) :', b[1,0]) # Print type and shape and values of the array

c = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]]) # Create a rank n array
print('\nn-d array : ')     
print(c)
print('type: ',type(c),' shape:', c.shape,' value at (0,0,1) :', c[0,0,1]) # Print type and shape and values of the array

1-d array (vector) :  [1 2 3]
type:  <class 'numpy.ndarray'>  shape: (3,)  value at (1) : 1

2-d array (matrice) : 
[[1 2]
 [3 4]]
type:  <class 'numpy.ndarray'>  shape: (2, 2)  value at (1,0) : 3

n-d array : 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
type:  <class 'numpy.ndarray'>  shape: (2, 2, 2)  value at (0,0,1) : 2


In [ ]:
# Other methods to create an array

print('Other methods to create an array : ')

print('\nCreating an array of all zeros - np.zeros((n,m)) : ')
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

print('\nCreating a 3-d array of all ones - np.ones((n,m)) : ')
b = np.ones((2,2,2))   # Create an array of all ones
print(b)

print('\nCreating a constant array - np.full((n,m),c) : ')
c = np.full((2,2), 7) # Create a constant array
print(c)

print('\nCreating an n\*n identity matrix - np.eye(n) : ')
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

print('\nCreating an array filled with random values between 0 and 1 - np.random.random((n,m)) : ')
e = np.random.random((2,2)) # Create an array filled with random values between 0 and 1
print(e)

Other methods to create an array : 

Creating an array of all zeros - np.zeros((n,m)) : 
[[0. 0.]
 [0. 0.]]

Creating a 3-d array of all ones - np.ones((n,m)) : 
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]

Creating a constant array - np.full((n,m),c) : 
[[7 7]
 [7 7]]

Creating an n\*n identity matrix - np.eye(n) : 
[[1. 0.]
 [0. 1.]]

Creating an array filled with random values between 0 and 1 - np.random.random((n,m)) : 
[[0.19737071 0.53960848]
 [0.87533119 0.07503855]]


In [ ]:
# Methods to create a vector

print('Other methods to create a vector : ')

print('\nCreating a vector, containing numbers from 0 to 10 with spaces of 1.5 - np.arange(0,10,1.5) : ')
a = np.arange(0,10,1.5)  # Create an array of all zeros
print(a)

print('\nCreating a vector, containing 6 numbers from 0 to 10 with equal spaces - np.linspace(0,10,6) : ')
a = np.linspace(0,10,6)  # Create an array of all zeros
print(a)

Other methods to create a vector : 

Creating a vector, containing numbers from 0 to 10 with spaces of 1.5 - np.arange(0,10,1.5) : 
[0.  1.5 3.  4.5 6.  7.5 9. ]

Creating a vector, containing 6 numbers from 0 to 10 with equal spaces - np.linspace(0,10,6) : 
[ 0.  2.  4.  6.  8. 10.]


In [ ]:
# Copying an array

x = np.array([[1, 2],
              [3, 4]])
print('Original array: ')
print(x)

print('Copied array - x.copy(): ')
y = x.copy()  # Also try y = x to see the difference...
print(y)

print('\nChanging the copied array values... ')
y[0,0]=100

print('\nOriginal array: ')
print(x)
print('Copied array: ')
print(y)

Original array: 
[[1 2]
 [3 4]]
Copied array - x.copy(): 
[[1 2]
 [3 4]]

Changing the copied array values... 

Original array: 
[[1 2]
 [3 4]]
Copied array: 
[[100   2]
 [  3   4]]


In [ ]:
# Reshaping an array

x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])
print('Base array: ')
print(x)

print('\nFlattened array to a 1-d vector - x.flatten() : ')
print(x.flatten()) 

print('\nReshaped array - x.reshape([2,6]) : ')
print(x.reshape([2,6]))

print('\nReshaped array - x.reshape([4,3]) : ')
print(x.reshape([4,3]))

Base array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened array to a 1-d vector - x.flatten() : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped array - x.reshape([2,6]) : 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshaped array - x.reshape([4,3]) : 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Methods to create arrays from another array

x = np.array([[1, 2],
              [3, 4]])
print('Base array: ')
print(x)

print('\nArray with zeros with same shape as base array - np.zeros_like(x): ')
print(np.zeros_like(x))

print('\nArray with ones with same shape as base array - np.ones_like(x): ')
print(np.ones_like(x))

print('\nArray with constants with same shape as base array - np.full_like(x, c): ')
print(np.full_like(x,100))

print('\nMake an array with given size, the place all of cells with a given array - np.tile(x, shape): ')
print(np.tile(x,[2,3]))


Base array: 
[[1 2]
 [3 4]]

Array with zeros with same shape as base array - np.zeros_like(x): 
[[0 0]
 [0 0]]

Array with ones with same shape as base array - np.ones_like(x): 
[[1 1]
 [1 1]]

Array with constants with same shape as base array - np.full_like(x, c): 
[[100 100]
 [100 100]]

Make an array with given size, the place all of cells with a given array - np.tile(x, shape): 
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


To see full documantion about array creation see [here](https://numpy.org/doc/stable/reference/routines.array-creation.html).

###Datatypes

In [ ]:
x = np.array([1, 2])                      # Let numpy choose the datatype
y = np.array([1.0, 2.0])                  # Let numpy choose the datatype
z = np.array([1.5, 2], dtype=np.float64)  # Force a particular datatype
#Some useful datatypes : np.bool8 , np.uint16 , np.int32 , np.float64 , np.complex128

print('x: ', x, '\ttype: ', x.dtype)
print('y: ', y, '\ttype: ', y.dtype)
print('z: ', z, '\ttype: ', z.dtype)

x:  [1 2] 	type:  int64
y:  [1. 2.] 	type:  float64
z:  [1.5 2. ] 	type:  float64


In [ ]:
# Convert a numpy array to another datatype.
x = np.array([1.7, 2.1])    
print('Array before converting to int : ', x)
x = x.astype(int)
print('Array after converting to int  : ', x)

Array before converting to int :  [1.7 2.1]
Array after converting to int  :  [1 2]


###Array indexing

In [ ]:
# Accessing different parts of the array.

a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])  # Create a rank 2 array
print('Whole array - a : ')
print(a)                 # Print the whole array

print('\nA point via its coordinates - a[0,2] : ')
print(a[0,2]) # Print a point via its coordinates

print('\nSome points via coordinates - a[[0,1],[0,2]] : ')
print(a[[0,1],[0,2]]) # Print some points via coordinates

print('\nA part of the array - a[0:2,1:3] : ')
print(a[0:2,1:3])        # Print a part of the array

print('\nSome columns of the array - a[:,[0,1]] : ')
print(a[:,[0,1]]) # Print some columns of the array

print('\nSome rows of the array - a[[0,1],:] : ')
print(a[[0,1],:]) # Print some rows of the array

Whole array - a : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

A point via its coordinates - a[0,2] : 
3

Some points via coordinates - a[[0,1],[0,2]] : 
[1 6]

A part of the array - a[0:2,1:3] : 
[[2 3]
 [5 6]]

Some columns of the array - a[:,[0,1]] : 
[[1 2]
 [4 5]
 [7 8]]

Some rows of the array - a[[0,1],:] : 
[[1 2 3]
 [4 5 6]]


**Ellipsis in indexing**

When you use ... in indexing multi dimentional arrays, it means just put as many : needed. for example if A has shape of (3,100,200,300,400) then (...,10) is equivalent to ( :  ,  :  ,  :  ,  :  ,  10) and (0,...,10) is equivalent to ( 0  ,  :  ,  :  ,  :  ,  10).

In [ ]:
# Ellipsis in indexing

a = np.arange(32).reshape([2,2,2,2,2])
print('a[0,:,:,:,0]')
print(a[0,:,:,:,0])
print('\na[0,...,0]')
print(a[0,...,0])

a[0,:,:,:,0]
[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]

a[0,...,0]
[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]


In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])  # Create a rank 2 array
print('Whole array before changing - a : ')
print(a)

print('\nChanging a part of the array - a[0:2,0:2] : ')
a[0:2,0:2] = np.array([[100,100],[100,100]])  # Changing a part of the array

print('\nWhole array after changing - a : ')
print(a)

Whole array before changing - a : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Changing a part of the array - a[0:2,0:2] : 

Whole array after changing - a : 
[[100 100   3]
 [100 100   6]
 [  7   8   9]]


###Mathematical operations

####Basic operations

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
print('First array: ')
print(x)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print('Second array: ')
print(y)

# Elementwise sum
print('\nElementwise sum - x+y : ')
print(x + y)
print('Elementwise sum - np.add(x, y) : ')
print(np.add(x, y))

# Elementwise difference
print('\nElementwise difference - x-y : ')
print(x - y)
print('Elementwise difference - np.subtract(x, y) : ')
print(np.subtract(x, y))

# Elementwise product
print('\nElementwise product - x*y : ')
print(x * y)
print('Elementwise product - np.multiply(x, y) : ')
print(np.multiply(x, y))

# Elementwise division
print('\nElementwise division - x/y : ')
print(x / y)
print('Elementwise division - np.divide(x, y) : ')
print(np.divide(x, y))

First array: 
[[1. 2.]
 [3. 4.]]
Second array: 
[[5. 6.]
 [7. 8.]]

Elementwise sum - x+y : 
[[ 6.  8.]
 [10. 12.]]
Elementwise sum - np.add(x, y) : 
[[ 6.  8.]
 [10. 12.]]

Elementwise difference - x-y : 
[[-4. -4.]
 [-4. -4.]]
Elementwise difference - np.subtract(x, y) : 
[[-4. -4.]
 [-4. -4.]]

Elementwise product - x*y : 
[[ 5. 12.]
 [21. 32.]]
Elementwise product - np.multiply(x, y) : 
[[ 5. 12.]
 [21. 32.]]

Elementwise division - x/y : 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
Elementwise division - np.divide(x, y) : 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


####Elementwise functions

In [ ]:
x = np.array([[1.5,2.5],[3.5,4]], dtype=np.float64)
print('First array: ')
print(x)

print('\nElementwise power root - np.power(x, 2) : ')
print(np.power(x, 2))
print('\nElementwise square root - np.sqrt(x) : ')
print(np.sqrt(x))
print('\nElementwise sinus - np.sin(x) : ')
print(np.sin(x))
print('\nElementwise floor - np.floor(x) : ')
print(np.floor(x))
print('\nElementwise log - np.log(x) : ')
print(np.log(x))

First array: 
[[1.5 2.5]
 [3.5 4. ]]

Elementwise power root - np.power(x, 2) : 
[[ 2.25  6.25]
 [12.25 16.  ]]

Elementwise square root - np.sqrt(x) : 
[[1.22474487 1.58113883]
 [1.87082869 2.        ]]

Elementwise sinus - np.sin(x) : 
[[ 0.99749499  0.59847214]
 [-0.35078323 -0.7568025 ]]

Elementwise floor - np.floor(x) : 
[[1. 2.]
 [3. 4.]]

Elementwise log - np.log(x) : 
[[0.40546511 0.91629073]
 [1.25276297 1.38629436]]


To see full documantion about these functions see [here](https://numpy.org/doc/stable/reference/routines.math.html).

####Linear algebra

In [ ]:
x = np.array([[1,2],[3,4]])
print('First array: ')
print(x)
y = np.array([[5,6],[7,8]])
print('Second array: ')
print(y)

# Inner product of matrices
print('\nInner product of matrices - np.dot(x, y) : ')
print(np.dot(x, y))
print('Inner product of matrices - x.dot(y) : ')
print(x.dot(y))
print('Inner product of matrices - x@y : ')
print(x@y)

# Transpose of matrices
print('\nTranspose of the first matrice - x.T : ')
print(x.T)

First array: 
[[1 2]
 [3 4]]
Second array: 
[[5 6]
 [7 8]]

Inner product of matrices - np.dot(x, y) : 
[[19 22]
 [43 50]]
Inner product of matrices - x.dot(y) : 
[[19 22]
 [43 50]]
Inner product of matrices - x@y : 
[[19 22]
 [43 50]]

Transpose of the first matrice - x.T : 
[[1 3]
 [2 4]]


In [ ]:
v = np.array([1,2,3,4])
print('Vector: ')
print(v)
x = np.array([[1,2],[3,4]])
print('Matrice: ')
print(x)

# Norm of matrices
print('\nSecond norm of the vector - np.linalg.norm(v, ord=2) : ', np.linalg.norm(v, ord=2))
print('Infinity norm of the vector - np.linalg.norm(v, ord=np.inf) : ', np.linalg.norm(v, ord=np.inf))
print('Frobenius norm of the matrice - np.linalg.norm(x, ord=\'fro\') : ', np.linalg.norm(x, ord='fro'))

print('\nCondition number of array x - np.linalg.cond(x) : ', np.linalg.cond(x))
print('Determinant of array x - np.linalg.det(x) : ', np.linalg.det(x))
print('Sum along diagonals of the array - np.trace(x) : ', np.trace(x))


print('\nMultiplicative inverse of a matrix - np.linalg.inv(x) : ')
print(np.linalg.inv(x))

print('\nEigenvalues and right eigenvectors of square array x - np.linalg.eig(x) : ')
print(np.linalg.eig(x))

Vector: 
[1 2 3 4]
Matrice: 
[[1 2]
 [3 4]]

Second norm of the vector - np.linalg.norm(v, ord=2) :  5.477225575051661
Infinity norm of the vector - np.linalg.norm(v, ord=np.inf) :  4.0
Frobenius norm of the matrice - np.linalg.norm(x, ord='fro') :  5.477225575051661

Condition number of array x - np.linalg.cond(x) :  14.933034373659268
Determinant of array x - np.linalg.det(x) :  -2.0000000000000004
Sum along diagonals of the array - np.trace(x) :  5

Multiplicative inverse of a matrix - np.linalg.inv(x) : 
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues and right eigenvectors of square array x - np.linalg.eig(x) : 
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


To see full documantion about linalg class see [here](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html).

####Broadcasting

Broadcasting is a mechanism to perform operations on arrays with diffrent shapes.

Suppose we have an n\*m matrice and we want to add each row of it to an n\*1 vector, we can copy the vector for m times and stack them together and add the result to the first matrice, but numpy does the same thing automatically (using broadcasting) as shown below: 

In [ ]:
x = np.array([[1,2],[3,4],[5,6]])
print('Matrice: ')
print(x)
v = np.array([100,200])
print('Vector: ')
print(v)

vv = np.tile(v, (3, 1))  # Stack 3 copies of v on top of each other
print('\nStacked vectors - : np.tile(v, (3, 1)) : ')
print(vv) 

print('\nSum of x and stacked vectors - x+vv : ')
print(x+vv)

print('\nSum of x and original vector, using broadcasting - x+v : ')
print(x+v)


Matrice: 
[[1 2]
 [3 4]
 [5 6]]
Vector: 
[100 200]

Stacked vectors - : np.tile(v, (3, 1)) : 
[[100 200]
 [100 200]
 [100 200]]

Sum of x and stacked vectors - x+vv : 
[[101 202]
 [103 204]
 [105 206]]

Sum of x and original vector, using broadcasting - x+v : 
[[101 202]
 [103 204]
 [105 206]]


And thats why you can add an array to an scalar or multiply an array by a different shape array.

In [ ]:
x = np.array([[1,2],[3,4]])
print('Matrice: ')
print(x)

print('\nSum of x and an scalar, using broadcasting - x+scalar : ')
print(x+100)

v = np.array([100,200])
print('\nVector: ')
print(v)
print('Product of x by a vector, using broadcasting - x*v : ')
print(x*v)

Matrice: 
[[1 2]
 [3 4]]

Sum of x and an scalar, using broadcasting - x+scalar : 
[[101 102]
 [103 104]]

Vector: 
[100 200]
Product of x by a vector, using broadcasting - x*v : 
[[100 400]
 [300 800]]


What this mechanism does is basicly it appends dimentions with lengh 1 to the shorter array (the array with less dimantions) to make arrays dimensions quantity, the same. then it loops on each dimention:



*   If the shapes in that dimention are the same, it does nothing.
*   If one of the shapes is 1, then it copies the array along that dimention until the arrays get same shape on that dimention.
*   If none of above cases happens, it raises an exception.



To see full documantion on broadcasting see [here](https://numpy.org/doc/stable/user/basics.broadcasting.html).

####Collective Functions (with axis parameter)

Applys a function to whole array and returns a number.

In [ ]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print('Array: ')
print(x)

print('\nSum of elements of matrice - np.sum(x) : ', np.sum(x))
print('Product of elements of matrice - np.product(x) : ', np.product(x))

print('\nMinimum of elements of matrice - np.min(x) : ', np.min(x))
print('Maximum of elements of matrice - np.max(x) : ', np.max(x))

print('\nAverage of elements of matrice - np.average(x) : ', np.average(x))
print('Median of elements of matrice - np.median(x) : ', np.median(x))
print('Variance of elements of matrice - np.var(x) : ', np.var(x))
print('standard deviation of elements of matrice - np.std(x) : ', np.std(x))
print('Norm of elements of matrice (norm of its flatten vector) - np.linalg.norm(x) : ', np.linalg.norm(x))

Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of elements of matrice - np.sum(x) :  45
Product of elements of matrice - np.product(x) :  362880

Minimum of elements of matrice - np.min(x) :  1
Maximum of elements of matrice - np.max(x) :  9

Average of elements of matrice - np.average(x) :  5.0
Median of elements of matrice - np.median(x) :  5.0
Variance of elements of matrice - np.var(x) :  6.666666666666667
standard deviation of elements of matrice - np.std(x) :  2.581988897471611
Norm of elements of matrice (norm of its flatten vector) - np.linalg.norm(x) :  16.881943016134134




**Axis parameter (in 2-d arrays)**

Collective functions have a parameter named axis; and you can change its value to a number (or a tuple) so the function will be applied along different axises.

For example if your array is a matrice (2-d array) by setting axis parameter of sum function to 0, you get an array that contains the values of sum of elements in each column. Similary by setting it to 1 you get the results in each row.

In [ ]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print('Array: ')
print(x)

print('\nSum of elements of matrice in each column - np.sum(x, axis=0) : ', np.sum(x, axis=0))
print('Sum of elements of matrice in each row - np.sum(x, axis=1) : ', np.sum(x, axis=1))
print('Sum of elements of matrice - np.sum(x, axis=[0,1]) : ', np.sum(x, axis=(0,1)))

Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of elements of matrice in each column - np.sum(x, axis=0) :  [12 15 18]
Sum of elements of matrice in each row - np.sum(x, axis=1) :  [ 6 15 24]
Sum of elements of matrice - np.sum(x, axis=[0,1]) :  45


**Axis parameter (in n-d arrays)**

For arrays with more than 2 dimentions its hard to imagine the array itself. The key to undrestand the axises is to look at the input and output shapes.

*Whatever indices we put in axises parameter, we loose those dimentions in the output.*

Let's say we have an array with shape (10,480,640,3) (for example an array of 10 RGB images with quality of 480\*640) and we want to calculate an average of this array in a way that the output be a (10,3) array (in our example, average of values of pixels in each picture and each RGB channel) so we want to remove second and third dimentions of the array; as a result, our axis in the average function must be (1,2) (indices start from 0)

You can see an example below: 

In [ ]:
x = np.random.random((10,480,640,3))
print('Original array shape: ', x.shape)

avg = np.average(x, axis=(1,2))
max = np.max(x, axis=(1,2))
sum = np.sum(x, axis=(1,2))

print("\nAverage array shape with axis=(1,2) - np.average(x, axis=(1,2)): ", avg.shape)
print("Max array shape with axis=(1,2) - np.max(x, axis=(1,2)):\t ", max.shape)
print("Sum array shape with axis=(1,2) - np.sum(x, axis=(1,2)):\t ", sum.shape)

Original array shape:  (10, 480, 640, 3)

Average array shape with axis=(1,2) - np.average(x, axis=(1,2)):  (10, 3)
Max array shape with axis=(1,2) - np.max(x, axis=(1,2)):	  (10, 3)
Sum array shape with axis=(1,2) - np.sum(x, axis=(1,2)):	  (10, 3)


###Advanced programming with numpy (using where function and comperative operators)

**Comparition of arrays**

You can compare two equl-shape arrays (or arrays that can broadcast together (see [broadcasting section](https://colab.research.google.com/drive/1HoFGxoKij1WqAkaMRUb0xVKUpfxkWxZJ?authuser=1#scrollTo=Phbf1lh4vIf2))
The result is an array of booleans that each cell's value, represents the result of comparition over corresponding cell's.

In [ ]:
a = np.array([[1,2],
              [3,4]])
print('First array: ')
print(a)

b = np.array([[2,2],
              [2,2]])
print('Second array: ')
print(b)

print('\nResult of comparision a<b : ')
print(a<b)
print('Result of comparision a>b : ')
print(a>b)
print('Result of comparision a==b : ')
print(a==b)

print('\nResult of comparision a<b and a<3 - np.logical_and(a<b, a<3): ')
print(np.logical_and(a<b, a<3))
print('Result of comparision a<b or a<3 - np.logical_or(a<b, a<3): ')
print(np.logical_or(a<b, a<3))
print('Result of comparision a<b xor a<3 - np.logical_xor(a<b, a<3): ')
print(np.logical_xor(a<b, a<3))
print('Result of comparision ~(a<b) - np.logical_not(a<b): ')
print(np.logical_not(a<b))

First array: 
[[1 2]
 [3 4]]
Second array: 
[[2 2]
 [2 2]]

Result of comparision a<b : 
[[ True False]
 [False False]]
Result of comparision a>b : 
[[False False]
 [ True  True]]
Result of comparision a==b : 
[[False  True]
 [False False]]

Result of comparision a<b and a<3 - np.logical_and(a<b, a<3): 
[[ True False]
 [False False]]
Result of comparision a<b or a<3 - np.logical_or(a<b, a<3): 
[[ True  True]
 [False False]]
Result of comparision a<b xor a<3 - np.logical_xor(a<b, a<3): 
[[False  True]
 [False False]]
Result of comparision ~(a<b) - np.logical_not(a<b): 
[[False  True]
 [ True  True]]


**np.where(cond)**

Suppose that you have a boolean array (an array with True/False elements) and you want to know which coordinates of it is True.

You can find the result with np.where(A) function:

In [ ]:
cond = np.array([[[True, False],
                  [False, True]],
                 [[True, True],
                  [False, False]]])
print('Coordinates of True values in each dimention: ', np.where(cond))

Coordinates of True values in each dimention:  (array([0, 0, 1, 1]), array([0, 1, 0, 0]), array([0, 1, 0, 1]))


This means there are 4 True values in the array. and their first dimention coordinates are [0, 0, 1, 1] and their second dimention coordinates are [0, 1, 0, 0] and their third dimention coordinates are [0, 1, 0, 1].
So if we pass these three vectors to the first array 
(see [array indexing](https://colab.research.google.com/drive/1HoFGxoKij1WqAkaMRUb0xVKUpfxkWxZJ?authuser=1#scrollTo=K8dqNsolRCvZ&line=3&uniqifier=1))
, we should get the 4 primal True values  :

In [ ]:
print(cond[np.where(cond)])

[ True  True  True  True]


If we combine all these concepts together we get a powerfull tool to calculate things, whithout looping over them.

Lets say we want to multiply every odd value of an array by two: 

In [ ]:
a = np.array([[1,2],
              [3,4]])
print('Array: ')
print(a)

a[np.where(a%2==1)] *= 2
print('Array after changing: ')
print(a)

Array: 
[[1 2]
 [3 4]]
Array after changing: 
[[2 2]
 [6 4]]


Or we want to change value of every element of an array that has a value bigger than 2, to -1:

In [ ]:
a = np.array([[1,2],
              [3,4]])
print('Array: ')
print(a)

a[np.where(a>2)] = -1
print('Array after changing: ')
print(a)

Array: 
[[1 2]
 [3 4]]
Array after changing: 
[[ 1  2]
 [-1 -1]]


As shown, working with numpy arrays are a little tricky, but after you get used to it, using numpy arrays is even simpler than writing nested loops.
so try to practice and get skilled in it. because as I showed you ([here](https://colab.research.google.com/drive/1HoFGxoKij1WqAkaMRUb0xVKUpfxkWxZJ?authuser=1#scrollTo=uhcmRjvYjSpi)), numpy arrays are so much faster than nested loops.

##Copyright: Mohammad Reza Bateni - 2022 ([LinkedIn](https://ir.linkedin.com/in/mohammad-reza-bateni-a58936142))([Email](mailto:Bateni1380@gmail.com))
